---
extends:
  - eslint:recommended
  - plugin:flowtype/recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  comma-dangle: [ "error", "always-multiline" ]
  no-var: "error"
  arrow-body-style: "error"
  padded-blocks: [ "error", "never" ]
  jsx-quotes: [ "error", "prefer-double" ]
  require-await: [ "error" ]
env:
  node: true
  browser: true
  es6: true
  mocha: true
plugins:
  - flowtype
globals:
  expect: false
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
